#!/usr/bin/env node
// Regenerates the "Per-prototype changelogs" block inside the root CHANGELOG.md
// from the per-prototype CHANGELOG.md files. Replaces the content between
// <!-- INDEX:START --> and <!-- INDEX:END --> markers.
//
// Runs on predev + prebuild — no manual editing of the index needed.

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')
const prototypesDir = join(repoRoot, 'src/prototypes')
const changelogPath = join(repoRoot, 'CHANGELOG.md')
const startMarker = '<!-- INDEX:START -->'
const endMarker = '<!-- INDEX:END -->'

function prettyName(slug) {
  return slug.split('-').map((w) => w[0].toUpperCase() + w.slice(1)).join(' ')
}

function lastEntryDate(changelogFile) {
  if (!existsSync(changelogFile)) return null
  const body = readFileSync(changelogFile, 'utf8')
  // Match the first "## YYYY-MM-DD" heading — per-prototype CHANGELOGs have
  // newest at top.
  const match = body.match(/^##\s+(\d{4}-\d{2}-\d{2})/m)
  return match ? match[1] : null
}

function listPrototypes() {
  return readdirSync(prototypesDir)
    .filter((name) => !name.startsWith('.') && !name.startsWith('_'))
    .filter((name) => statSync(join(prototypesDir, name)).isDirectory())
    .sort()
}

function buildTable() {
  const rows = []
  rows.push('| Prototype | Last updated | Changelog |')
  rows.push('|-----------|--------------|-----------|')
  for (const slug of listPrototypes()) {
    const changelog = join(prototypesDir, slug, 'CHANGELOG.md')
    const rel = `src/prototypes/${slug}/CHANGELOG.md`
    const last = lastEntryDate(changelog) ?? '—'
    const link = existsSync(changelog) ? `[${rel}](${rel})` : `_missing_`
    rows.push(`| ${prettyName(slug)} | ${last} | ${link} |`)
  }
  return rows.join('\n')
}

function main() {
  if (!existsSync(changelogPath)) {
    console.error('✗ root CHANGELOG.md not found')
    process.exit(1)
  }

  const body = readFileSync(changelogPath, 'utf8')
  const table = buildTable()
  const block = `${startMarker}\n\n${table}\n\n_Auto-generated by \`scripts/generate-index.mjs\` — do not edit by hand._\n\n${endMarker}`

  if (!body.includes(startMarker) || !body.includes(endMarker)) {
    console.error(`✗ Could not find ${startMarker} / ${endMarker} markers in CHANGELOG.md. Add them around the index section.`)
    process.exit(1)
  }

  const pattern = new RegExp(`${startMarker}[\\s\\S]*?${endMarker}`)
  const next = body.replace(pattern, block)
  if (next === body) {
    console.log('✓ Changelog index unchanged')
    return
  }
  writeFileSync(changelogPath, next)
  console.log('✓ Regenerated per-prototype changelog index in CHANGELOG.md')
}

main()
