/**
 * Icons — all from lucide-react.
 * Re-exported with the project's naming conventions so every import site stays the same.
 * VintigaLogoIcon is the only exception — it's the brand mark, not a UI icon.
 */

export {
  Info           as InfoIcon,
  ArrowLeft      as BackArrowIcon,
  Check          as CheckIcon,
  CircleCheck    as CheckCircleIcon,
  Search         as SearchIcon,
  Plus           as PlusIcon,
  ArrowRight     as ArrowRightIcon,
  Briefcase      as BriefcaseIcon,
  User           as UserIcon,
  Clock          as ClockIcon,
  ShieldCheck    as ShieldCheckIcon,
  CreditCard     as CreditCardIcon,
  House          as HomeIcon,
  Receipt        as ReceiptIcon,
  Wifi           as WifiIcon,
  Signal         as SignalIcon,
  Battery        as BatteryIcon,
  ChevronRight   as ChevronRightIcon,
  ChevronDown    as ChevronDownIcon,
  TriangleAlert  as WarningIcon,
  Sparkles       as SparklesIcon,
  TrendingUp     as TrendingUpIcon,
  ArrowDownAZ    as SortAZIcon,
  Globe          as GlobeIcon,
  Pencil         as PencilIcon,
  Pen            as PenIcon,
  Calendar       as CalendarIcon,
  Lock           as LockIcon,
  Wallet         as WalletIcon,
  ChartNoAxesColumnIncreasing as ChartIcon,
  ArrowLeftRight as ArrowLeftRightIcon,
  Bell           as BellIcon,
  Filter         as FilterIcon,
  Folder         as FolderIcon,
  Inbox          as InboxIcon,
  CalendarCheck  as CalendarCheckIcon,
  MessagesSquare as MessagesSquareIcon,
  Goal           as GoalIcon,
  Target         as TargetIcon,
  ChartColumn    as ChartColumnIcon,
  TrendingUp     as TrendUpIcon,
  PiggyBank      as PiggyBankIcon,
  Calculator     as CalculatorIcon,
  Telescope      as TelescopeIcon,
  Users          as UsersGroupIcon,
  Shield         as ShieldIcon,
  ChevronsUpDown as ChevronUpDownIcon,
  UserX          as UserXIcon,
  ChevronLeft    as ChevronLeftIcon,
  BookOpen       as BookOpenIcon,
  Bot            as BotIcon,
  Ellipsis       as EllipsisIcon,
  Box            as BoxIcon,
  Settings       as SettingsIcon,
  CircleHelp     as HelpIcon,
  PanelLeft      as SidebarIcon,
  MapPin         as MapPinIcon,
  Phone          as PhoneIcon,
  Mail           as MailIcon,
  Building2      as BuildingIcon,
  DollarSign     as DollarIcon,
  Upload         as ExportIcon,
  Eye            as EyeIcon,
  FileText       as FileTextIcon,
  Percent        as PercentIcon,
  TriangleAlert  as AlertTriangleIcon,
  X              as XIcon,
  Menu           as MenuIcon,
  BookUser       as PassportIcon,
  IdCard         as IdCardIcon,
  UserPen        as UserPenIcon,
  CircleAlert    as CircleAlertIcon,
  CircleX        as CircleXIcon,
  Trash2         as TrashIcon,
  Circle         as CircleIcon,
  EyeOff         as EyeOffIcon,
  Copy           as CopyIcon,
  CloudUpload    as CloudUploadIcon,
  Fingerprint    as FingerprintIcon,
  ScanFace       as ScanFaceIcon,
  LockOpen       as LockOpenIcon,
  Delete         as DeleteIcon,
  Hash           as HashIcon,
  MessageSquare  as MessageIcon,
  Send           as SendIcon,
  Tag            as TagIcon,
  Star           as StarIcon,
  Users          as UsersIcon,
  Package        as PackageIcon,
  ShoppingCart   as ShoppingCartIcon,
  Bookmark       as BookmarkIcon,
  ExternalLink   as ExternalLinkIcon,
  Italic         as ItalicIcon,
  Bold           as BoldIcon,
  Underline      as UnderlineIcon,
  Undo2          as UndoIcon,
  Redo2          as RedoIcon,
  AlignLeft      as AlignLeftIcon,
  AlignCenter    as AlignCenterIcon,
  AlignRight     as AlignRightIcon,
  AlignJustify   as AlignJustifyIcon,
  Link           as LinkIcon,
  Image          as ImageIcon,
  Upload         as UploadIcon,
  PackagePlus    as PackagePlusIcon,
  ListPlus       as ListPlusIcon,
  GripVertical   as GripVerticalIcon,
  Download       as DownloadIcon,
  LogOut         as LogOutIcon,
  ArrowUp        as ArrowUpIcon,
  ArrowDown      as ArrowDownIcon,
  // Product category icons
  BottleWine     as BottleWineIcon,
  Beer           as BeerIcon,
  Martini        as MartiniIcon,
  Wine           as WineIcon,
  PartyPopper    as PartyPopperIcon,
  Shirt          as ShirtIcon,
  HandHeart      as HandHeartIcon,
  Sandwich       as SandwichIcon,
  PackageOpen    as PackageOpenIcon,
  Gift           as GiftIcon,
  NotebookPen    as NotebookPenIcon,
  Ticket         as TicketIcon,
} from 'lucide-react'

import type { SVGProps } from 'react'

// ── Brand mark — not a UI icon, keep as custom SVG ───────────────────────────
export function VintigaLogoIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="44" height="44" viewBox="0 0 44 44" fill="none" {...props}>
      <path fillRule="evenodd" clipRule="evenodd" d="M7.71144 5.5L4.125 38.4994H12.4436L16.0287 5.5H7.71144Z" fill="currentColor"/>
      <path fillRule="evenodd" clipRule="evenodd" d="M28.515 5.50065L22.5378 18.3321L18.0518 8.40082L16.3368 25.0406L22.5378 38.5L29.1086 24.9337H29.1984L31.1153 38.5H39.875L35.3609 5.50065H28.515Z" fill="currentColor"/>
    </svg>
  )
}
